CREATE TABLE IF NOT EXISTS chart_of_accounts (
  code VARCHAR(20) PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wage_codes (
  code VARCHAR(4) PRIMARY KEY,
  description VARCHAR(100) NOT NULL,
  category VARCHAR(60) NOT NULL,
  attached_account_code VARCHAR(20) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_wage_codes_chart_account
    FOREIGN KEY (attached_account_code) REFERENCES chart_of_accounts(code)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);
